### ISSUE TITLE
Modules can't be imported

### ISSUE THREAD

**Issue by JuanCaicedo** [billperegoy/elm-quickstart#1]
This works great if I use `$ npm run watch` however, I tried running `$ elm-make src/Main.elm` and get the following error

```
I cannot find module 'Utils'.

Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json
```

**Comment by billperegoy** [comment]
Juan,
   I believe you need to run:

$ elm-make src/*.elm

Otherwise elm-make will not know to also compile Utils.elm.

Please let me know if that works for you.
